version: "2.2"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${DATA_PATH}:/home/database/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    networks:
      - app-network

  kib01:
    image: docker.elastic.co/kibana/kibana:7.13.4
    container_name: kib01
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kib03.rule=Host(`kibana.dixeam.com`)"
      - "traefik.http.services.kib03.loadbalancer.server.port=5601"
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
      xpack.security.enabled: true
    networks:
      - app-network

networks:
  app-network:
    external: true
